### ISSUE TITLE
Containerize the API and update Readme

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/task-management-system#10]
**Description**
You are required to containerize the api, update readme, and complete testing.

**Task to do**
- [ ] complete testing by adding integration test and e2e test
- [ ] update the README to include compelete setup and reflect app state
- [ ] containerize the api using docker

**Acceptance Criteria**
- [ ] Unit and integration tests that covers the full scope and edge cases of app
- [ ] clear, concise README that provides setup instruction and how to use the app
- [ ] dockerfile and docker compose file that can be used to start the app
