### ISSUE TITLE
Create API endpoints for CRUD operations

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/task-management-system#3]
**Description**
Your are required to build the following crud endpoints to manage tasks.

**Endpoints**
- POST /tasks: create a new task
- GET /tasks: Retrieve all tasks (with pagination)
- GET /tasks/:id : Retrieve a task by its ID
- PUT /tasks/:id : Update an existing task by id
- DELETE /tasks/:id: Delete a task by id

**User Model**
- Id (UUID): unique user identifier
- email (String): Must be unique for each user
- username (optional, String): must be Unique.
- password (hashed String): securely Stored user password

**Task Model**
- title (string): The task's title
- description (string): Detailed task description
- dueDate(date): The deadline for the task
- status(string): Task status. Acceptance values are 'pending', 'in-progress', or 'completed'
- createdAt and updateAt: Automatically handled by the system.

**Acceptance Criteria**
- [ ] An api that allows users to create, read, update and delete tasks.
- [ ] proper error handling
- [ ] proper input validation
- [ ] proper unit testing
