### ISSUE TITLE
Implement task filtering and sharing

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/task-management-system#9]
**Description**
You are required to add task filtering and assigning a task to a user using their email

**Task to be done**
- [ ] Allow user to filter task by status, priority and tags
- [ ] Enable users to share task with other users using their email address

**Endpoints**
- filtering endpoint: `GET /tasks?status=pending&priority=high`
- sharing endpoint: `PUT  /tasks/share`

**Acceptance Criteria**
- [ ]  User should be able to filter task by status, priority and tags
- [ ] User should be able to share a task they own
- [ ] Proper unit test coverage of implementation
